INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('Xbox One', '/Content/xbox_icon.png', 1);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('PS4', '/Content/ps4_icon.png', 2);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('Wii U', '/Content/wiiu_icon.png', 3);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('Xbox 360', '/Content/xbox360_icon.png', 4);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('PS3', '/Content/ps3_icon.png', 5);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('Wii', '/Content/wii_icon.png', 6);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('3DS', '/Content/3ds_icon.png', 7);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('PS Vita', '/Content/psvita_icon.png', 8);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('DS', '/Content/ds_icon.png', 9);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('PSP', '/Content/psp_icon.png', 10);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('Xbox', '/Content/xbox_original_icon.png', 11);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('PS2', '/Content/ps2_icon.png', 12);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('Gamecube', '/Content/gamecube_icon.png', 13);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('GBA', '/Content/gba_icon.png', 14);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('PS1', '/Content/ps1_icon.png', 15);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('Game Boy', '/Content/gameboy_icon.png', 16);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('N64', '/Content/n64_icon.png', 17);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('PC', '/Content/pc_icon.png', 18);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('Mac', '/Content/mac_icon.png', 19);
INSERT INTO Categories(Name, IconUrl, CategoryOrder) VALUES ('Linux', '/Content/linux_icon.png', 20);
INSERT INTO Publishers(Name) VALUES ('EA');
INSERT INTO Products(Name, Description, ImageUrl, Price, ReleaseDate, Featured, CategoryID, PublisherID) VALUES ('FIFA 16', 'Get ready for this year''s latest installment in the famous soccer franchise. With updated team rosters and all new features, this is undoubtedly geared to be the best FIFA game to date.', '/Content/fifa16.jpg', 59.99, '09/22/15', 1, 1, 1);
