//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneStopGaming
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartsPromotion
    {
        public int ID { get; set; }
        public int PromotionID { get; set; }
        public int CartID { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
